# 服务端口
server:
  port: 8009
# 服务名
spring:
  profiles:
    active: dev # 环境设置 dev:开发 test:测试 prod:生产
  application:
    name: service-acl
  datasource:  #mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_guli_acl?serverTimezone=GMT%2B8
    username: root
    password: root
#返回json的全局时间格式
#spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
#spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    password:  #默认为空
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0
#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/learn/acl/mapper/xml/*.xml
