server:
  port: 8001  #服务端口
  tomcat:
    max-threads: 10 #tomcat的最大并发值修改为10,默认是200

spring:
  profiles:
    active: dev  #环境设置 dev:开发 test:测试 prod:生产
  application:
    name: service-edu  #服务名
  datasource:  #mysql数据库连接
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_guli?serverTimezone=GMT%2B8
    username: root
    password: root
#返回json的全局时间格式
#spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
#spring:
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  #nacos服务地址
    sentinel:
      transport:
        port: 8081  #跟控制台交流的端口，随意指定一个未使用的端口即可
        dashboard: localhost:8080  #指定控制台服务的地址
# 设置日志级别
#logging.level.root=INFO

#mybatis日志
#mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
#mybatis日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:com/learn/eduservice/mapper/xml/*.xml

#service-oss: # 调用的提供者的名称
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  MaxAutoRetries: 0 # 同一实例最大重试次数，不包括首次调用，默认0
  MaxAutoRetriesNextServer: 1 # 重试其他实例的最大重试次数，不包括首次所选的server，默认1
  ConnectTimeout: 5000 #连接建立的超时时长，默认1秒
  ReadTimeout: 5000 #处理请求的超时时间，默认为1秒
feign:
  sentinel:
    enabled: true
